# Test differential geometry operations using sphere test case

Try 1-D sphere as first example...

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import collections, lines, path, patches
%matplotlib inline

## Adding vectors in tangent space

In [4]:
from geometry import *

## Tests of dot:
Null vector dotted with unit vector, expect zero in all cases

In [9]:
u = np.ones([1,1])
print(u.shape)
v = np.zeros([1,1])
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)
            )
         )

(1, 1)
u.T.shape = (1, 1), v.shape = (1, 1), metric.shape = (1, 1)
Original dot = [[0.]]
u.T.shape = (1, 1), v.shape = (1, 1), metric.shape = (1, 1)
Original dot = [[-0.]]


Dot parallel unit vectors, expect two in euclidean and zero in hyperbolic cases.

In [12]:
u = np.ones([2, 1])
v = np.ones([2, 1])
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)))

u.T.shape = (1, 2), v.shape = (2, 1), metric.shape = (2, 2)
Original dot = [[2.]]
u.T.shape = (1, 2), v.shape = (2, 1), metric.shape = (2, 2)
Original dot = [[0.]]


Dot anti-parallel unit vectors, expect Euclidean - -2 and hyperbolic = 0.

In [13]:
v = -v
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)))

u.T.shape = (1, 2), v.shape = (2, 1), metric.shape = (2, 2)
Original dot = [[-2.]]
u.T.shape = (1, 2), v.shape = (2, 1), metric.shape = (2, 2)
Original dot = [[0.]]


Dot perpendicular vectors, expect zero in Euclidean case and two in hyperbolic

In [16]:
u = np.ones([2,1])
v = np.array([[1, -1]]).T
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)))

u.T.shape = (1, 2), v.shape = (2, 1), metric.shape = (2, 2)
Original dot = [[0.]]
u.T.shape = (1, 2), v.shape = (2, 1), metric.shape = (2, 2)
Original dot = [[2.]]


In [19]:
u = np.hstack([np.ones([2,1]), np.array([[1, -1]]).T])

In [20]:
print(u)

[[ 1.  1.]
 [ 1. -1.]]


In [23]:
print(u.T)

[[ 1.  1.]
 [ 1. -1.]]


In [24]:
v = np.hstack([np.ones([2,1]), np.array([[0, -1]]).T])
print(v)

[[ 1.  0.]
 [ 1. -1.]]


In [22]:
dot(u, v)

u.T.shape = (2, 2), v.shape = (2, 2), metric.shape = (2, 2)


array([[ 2., -1.],
       [ 0.,  1.]])

In [27]:
np.sum(u[:, 0]*v[:,0])

2.0