# Test differential geometry operations using sphere test case

Try 1-D sphere as first example...

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import collections, lines, path, patches
%matplotlib inline

## Adding vectors in tangent space

In [2]:
from geometry import *

## Tests of dot:
Null vector dotted with unit vector, expect zero in all cases

In [3]:
u = np.ones([1,1])
print(u.shape)
v = np.zeros([1,1])
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)
            )
         )

(1, 1)
Original dot = [[0.]]
Original dot = [[-0.]]


Dot parallel unit vectors, expect two in euclidean and zero in hyperbolic cases.

In [4]:
u = np.ones([2, 1])
v = np.ones([2, 1])
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)))

Original dot = [[2.]]
Original dot = [[0.]]


Dot anti-parallel unit vectors, expect Euclidean - -2 and hyperbolic = 0.

In [5]:
v = -v
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)))

Original dot = [[-2.]]
Original dot = [[0.]]


Dot perpendicular vectors, expect zero in Euclidean case and two in hyperbolic

In [6]:
u = np.ones([2,1])
v = np.array([[1, -1]]).T
for geometry in ["spherical", "hyperbolic"]:
    print("Original dot = {}".format(
            dot(u, v, geometry)))

Original dot = [[0.]]
Original dot = [[2.]]


In [7]:
u = np.hstack([np.ones([2,1]), np.array([[1, -1]]).T])

In [8]:
print(u)

[[ 1.  1.]
 [ 1. -1.]]


In [9]:
print(u.T)

[[ 1.  1.]
 [ 1. -1.]]


In [10]:
v = np.hstack([np.ones([2,1]), np.array([[0, -1]]).T])
print(v)

[[ 1.  0.]
 [ 1. -1.]]


In [11]:
dot(u, v)

array([[ 2., -1.],
       [ 0.,  1.]])

In [12]:
np.sum(u[:, 0]*v[:,0])

2.0

In [31]:
def dot_einsum(u, v, geometry="spherical"):
    '''
        Calculate dot_product for two n-D vectors, u and v
        Inputs: u, v: two [n,1] vectors, or arrays of vectors,
        Outputs: dot_product, a 1-D real number (np.float32), or array thereof
    '''
#    if u.shape.ndims != 1 or v.shape.ndims != 1:
#        raise TypeError(
#                            "dot only supports vectors, but"
#                            " u.shape = {} and v.shape = {}".format(
##                                u.shape, v.shape
#                            )
#        )

    metric = get_metric(u.shape[0], geometry)
 #   mega_metric = np.einsum("ij,kl->ijkl", metric, metric)
    return np.einsum("ij,ia,jb->ab", metric, u, v)

In [32]:
u = np.ones([2,1])
v = np.array([[1, -1]]).T
for geometry in ["spherical", "hyperbolic"]:
    print("dot_einsum = {}".format(
            dot_einsum(u, v, geometry)))

dot_einsum = [[0.]]
dot_einsum = [[2.]]


In [33]:
u = np.hstack([np.ones([2,1]), np.array([[1, -1]]).T])
v = np.hstack([np.ones([2,1]), np.array([[0, -1]]).T])

In [35]:
dot_einsum(u, v, geometry="hyperbolic")

array([[ 0.,  1.],
       [ 2., -1.]])